name: Check
on: [ pull_request, push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        db: [mysql, postgresql, redshift, sqlserver]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: "gradle"
      - name: Setup database
        run: docker compose up -d ${{ matrix.services }}
      - name: Build with testing
        run: ./gradlew --stacktrace :embulk-output-${{ matrix.services }}:check
        env:
          _JAVA_OPTIONS: "-Xmx2048m -Xms512m"
          EMBULK_OUTPUT_TEST_CONFIG: "${{ github.workspace }}/ci/${{ matrix.services }}.yml"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mysql
          path: embulk-output-${{ matrix.services }}/build/reports/tests/test
